### ISSUE TITLE
Readme.md - "make run" error on macOS Sierra

### ISSUE THREAD

**Issue by davidhortonweb** [Automattic/wp-calypso-bootstrap#11]
I am running macOS Sierra.  Upon following instructions to install and setup, everything installed fine.  After accessing calypso via SSH and navigating to /var/sources, I was unable to run the "make run" command.  I received the following error:

`make: *** No rule to make target 'run.  Stop.`

However, when I issued the "npm start" command, everything loaded successfully and I could access the site locally.  I noticed there was no makefile in the directory.  Am I missing something due to an OSX configuration?  Should there be a makefile in this directory?

Thank you so much!

**Comment by davidhortonweb** [comment]
Just noticed issue (#14631) on the wp-calypso repository https://github.com/Automattic/wp-calypso/pull/14631/files removing makefile functionality.

**Comment by stephanethomas** [comment]
This was fixed by https://github.com/Automattic/wp-calypso/pull/14631.
